Iter 6
llravell/simple-cards pull request #1
Opened 2024-12-23 12:58 UTC by llravell

2024-12-23 19:23 UTC, llravell commented on internal/controller/http/health/health.go
> +package health
Копипаста с прошлого проекта

2024-12-23 19:23 UTC, llravell commented on internal/controller/http/health/health_test.go
> +package health_test
Копипаста с прошлого проекта

2024-12-23 19:23 UTC, llravell commented on internal/controller/http/middleware/compress.go
> +package middleware
Копипаста с прошлого проекта

2024-12-23 19:23 UTC, llravell commented on internal/controller/http/middleware/compress_test.go
> +package middleware_test
Копипаста с прошлого проекта

2024-12-23 19:23 UTC, llravell commented on internal/controller/http/middleware/logger.go
> +package middleware
Копипаста с прошлого проекта

2024-12-23 19:23 UTC, llravell commented on internal/controller/http/middleware/logger_test.go
> +package middleware_test
Копипаста с прошлого проекта

2024-12-23 19:24 UTC, llravell commented on internal/usecase/health.go
> +package usecase
Копипаста с прошлого проекта

2024-12-23 19:24 UTC, llravell commented on logger/logger.go
> +package logger
Копипаста с прошлого проекта

2024-12-23 19:25 UTC, llravell commented on pkg/workerpool/workerpool.go
> +package workerpool
Копипаста с прошлого проекта

2024-12-28 16:30 UTC, bulbetski requested changes
Слишком хорошо написано, вообще не прикопаться, но все-таки пара мелочей есть

2024-12-28 16:30 UTC, bulbetski commented on migrations/20241207134039_create_table_users.sql
> +  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
добавь ко всем тамйтемпам with timezone

2024-12-28 16:30 UTC, bulbetski commented on cmd/simplecards/main.go
> +func main() {
ваще шик, вот песня прям. (репозитории, юзкейсы итд)

2024-12-28 16:30 UTC, bulbetski commented on internal/app/app.go
> +	cardsUseCase   *usecase.CardsUseCase
Вот это всё надо передавать в качестве интерфейсов. То есть где-нибудь сверх создать интерфейсы, которые будут реализовать только необходимые методы из твоих юзкейсов.
Одним из ключевых поинтов использования интерфейсов является ограничение контрактов до минимального кол-ва методов необходимого твоей структуре. 
То есть теоретически разные методы твоего одного юзкейс могут использоваться в разных структурах и тогда надо только их в интерфейсе писать.

Если же используются все методы, то можешь какой-нибудь отдельный файл сделать для интерфейсов

2024-12-28 16:30 UTC, bulbetski commented on internal/app/app.go
> +func (app *App) Run() {
стоить разделить создание рутов и запуск приложения

2024-12-28 16:30 UTC, bulbetski commented on internal/app/app.go
> +	cardsRoutes := cards.NewRoutes(app.modulesUseCase, app.cardsUseCase, app.log)
Насчет разделения хэндлеров на отдельные структуры не уверен. Конечно, имеет место быть, но можно как бы этого и не делать. Часто бывает, что разные юзкейсы могут в одном хэндлере оказаться, тут тогда муторно будет

(на твое усмотрение)

2024-12-28 16:30 UTC, bulbetski commented on internal/controller/http/auth/auth.go
> +	var requestData authRequest
Добавить бы какую-нибудь базовую валидацию на поля твоего запроса. Одного decode недостаточно

2024-12-28 16:30 UTC, bulbetski commented on internal/controller/http/auth/auth.go
> +}
Можно вынести в отдельный пакет models/requests/dto вместе со всеми подобными структурами. При этом не обязательно разделять сущности пакетами, можно их пазделить просто файлами models/auth models/cards итд

2024-12-28 16:30 UTC, bulbetski commented on internal/controller/http/auth/auth.go
> +	var requestData authRequest
Кароч этот коммент будет ко всем методам. Везде надо валидировать входные параметры и возвращать bad request. Убедись сам, я дальше пропускать буду

2024-12-28 16:30 UTC, bulbetski commented on internal/repository/cards_psql.go
> +		}
всегда лучше возвращать nil, err, чтобы снаружи не ожидали, так скажем, что можно получить какой-то валидный ответ несмотря на ошибку

2024-12-28 16:30 UTC, bulbetski commented on internal/repository/cards_psql.go
> +	return &storedCard, err
Давай сначала обработаем if err != nil, а потом вернем &storedCard, nil в случае ошибки, так прозрачнее

2024-12-28 16:30 UTC, bulbetski commented on internal/repository/cards_psql.go
> +	return &storedCard, err
(1 раз пишу, мест много таких)

2025-01-08 14:05 UTC, llravell commented on internal/app/app.go
> +	cardsRoutes := cards.NewRoutes(app.modulesUseCase, app.cardsUseCase, app.log)
А как можно иначе переиграть?
Сделать единую структуру для всех роутов?

2025-01-11 11:48 UTC, bulbetski commented on internal/app/app.go
> +	cardsRoutes := cards.NewRoutes(app.modulesUseCase, app.cardsUseCase, app.log)
Ну типа того. Но опять же, можно этого и не делать

2025-01-11 11:53 UTC, bulbetski approved these changes
Теперь всё норм, не придраться

2025-01-12 14:32 UTC, merged